export default {
    API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
    GOOGLE_MAPS_API_ENDPOINT: process.env.REACT_APP_GOOGLE_MAPS_API_ENDPOINT,
    GOOGLE_MAPS_API_KEY: process.env.REACT_APP_GOOGLE_MAPS_API_KEY
}